name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout only keytool folder
        uses: actions/checkout@v4
      - name: Set Directory
        run: cd keytool

      - name: Run Clippy with warnings as errors
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Auto-fix Clippy warnings
        run: cargo clippy --fix -Z unstable-options --allow-dirty --allow-staged

      - name: Run tests
        run: cargo test --all

      - name: Build
        run: cargo build --release

      - name: Upload keytool artifact
        uses: actions/upload-artifact@v4
        with:
          name: keytool-folder
          path: keytool/
